### ISSUE TITLE
NPE onPause issue

### ISSUE THREAD

**Issue by duggalsu** [itkach/aard2-android#116]
I get the following error on switching apps on Android 11

```
W/MainActivity: Hiding soft input failed
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.IBinder android.view.View.getWindowToken()' on a null object reference
        at itkach.aard2.MainActivity.onPause(MainActivity.java:202)
        at android.app.Activity.performPause(Activity.java:8174)
        at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1510)
        at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4735)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4696)
        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4647)
        at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:46)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ExecInit.main(ExecInit.java:43)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)

```

**Comment by itkach** [comment]
That's a warning, it's nothing new and shouldn't break anything
