### ISSUE TITLE
App crashes sometimes when user comes back to it after a period of inactivity

### ISSUE THREAD

**Issue by itkach** [itkach/aard2-android#14]
App crashes with the following exception in the log:
```
01-03 15:48:21.453    9016-9086/itkach.aard2 E/AndroidRuntime﹕ FATAL EXCEPTION: Timer-0
    Process: itkach.aard2, PID: 9016
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.post(java.lang.Runnable)' on a null object reference
            at itkach.aard2.ArticleWebView$2$1.run(ArticleWebView.java:114)
            at java.util.Timer$TimerImpl.run(Timer.java:284)
```

**Comment by itkach** [comment]
Fixed in 7a18c5bdb7a88a54c3836eadf655c03af6592011
