### ISSUE TITLE
App Exception When click the dictionary

### ISSUE THREAD

**Issue by androidAppGuard** [itkach/aard2-android#144]
### We found a exception when testing the app, and the environment is as follows:
      App version: 0.40
      Android version: 6.0
      Device: Nexux_5X
### The steps to reproduce:
![3_aard2_NullPointerException.gif](https://s2.loli.net/2022/05/12/bcPF6Xd5qJzAGBI.gif)
### The Exception log is as follows:
05-12 07:02:18.044 8749-8749/itkach.aard2 W/MainActivity: Hiding soft input failed
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.IBinder android.view.View.getWindowToken()' on a null object reference
        at itkach.aard2.MainActivity.onPause(MainActivity.java:202)
        at android.app.Activity.performPause(Activity.java:6348)
        at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1311)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3367)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3340)
        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3315)
        at android.app.ActivityThread.-wrap13(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by itkach** [comment]
this is not an issue
