### ISSUE TITLE
App crashes on Android 4.1.2

### ISSUE THREAD

**Issue by data-man** [itkach/aard2-android#15]
Crashes when user clicking on founded item.
v. 0.11 works fine.

**Comment by itkach** [comment]
Which item, lookup result? Any or some? Any dictionary? Do bookmarks and history open or also crash? Have stack trace?

**Comment by data-man** [comment]
А можно по-русски спрошу? :)
Да, в результатах поиска, в любом словаре. И из истории и из закладок тоже падает.

А где лежит лог?

**Comment by itkach** [comment]
Looks like API level compatibility issue:

   java.lang.NoSuchMethodError: itkach.aard2.ArticleCollectionActivity.isDestroyed
            at itkach.aard2.ArticleCollectionActivity$2.onPostExecute(ArticleCollectionActivity.java:111)
            at itkach.aard2.ArticleCollectionActivity$2.onPostExecute(ArticleCollectionActivity.java:79)
            at android.os.AsyncTask.finish(AsyncTask.java:631)
            at android.os.AsyncTask.access$600(AsyncTask.java:177)
            at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4745)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)

[Activity.html#isDestroyed()](http://developer.android.com/reference/android/app/Activity.html#isDestroyed%28%29) was added in API level 17 and your device is 16.

**Comment by itkach** [comment]
> А можно по-русски спрошу?

Можно, но тогда гораздо меньше людей может участвовать.

> А где лежит лог?

Просто так - кажется нигде. Лог наблюдать можно посредством [adb](https://developer.android.com/tools/help/adb.html), `adb logcat`.

**Comment by data-man** [comment]
Но версия 0.11 таких проблем не имеет.
Это только в последних двух появилось.
Можно как-то проверять версию API и подстраиваться под неё?

**Comment by itkach** [comment]
Fixed in 1de6408241df798eb60b6e78b595e1ef41a66c47, [give it a try](https://github.com/itkach/aard2-android/releases/tag/0.14)

**Comment by data-man** [comment]
Thanks, all o.k.!
