### ISSUE TITLE
Aard2 fails to view articles in Gesner Latin dictionary

### ISSUE THREAD

**Issue by LRN** [itkach/aard2-android#166]
See https://github.com/latin-dict/Gesner1749/releases

```
java.lang.NullPointerException: Attempt to invoke interface method 'byte[] itkach.slob.Slob$Compressor.decompress(byte[])' on a null object reference
	at itkach.slob.Slob$StoreItem.getBinItem(Slob.java:626)
	at itkach.slob.Slob$StoreItem.access$300(Slob.java:611)
	at itkach.slob.Slob$Store.getContentData(Slob.java:682)
	at itkach.slob.Slob.getContent(Slob.java:902)
	at itkach.slob.Slob.getContent(Slob.java:898)
	at itkach.slobber.Slobber$4.GET(Slobber.java:527)
	at itkach.slobber.Slobber$GETContainer.handle(Slobber.java:77)
	at itkach.slobber.Slobber.handle(Slobber.java:618)
	at org.simpleframework.http.core.RequestDispatcher.dispatch(RequestDispatcher.java:121)
	at org.simpleframework.http.core.RequestDispatcher.run(RequestDispatcher.java:103)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
```

Now, it's quite possible that the dictionary is poorly-formed, but i have no way to check that.

**Comment by itkach** [comment]
> Now, it's quite possible that the dictionary is poorly-formed

it is. Here's the header (retrieved with `slob` or aard2-web): 

```
         id: 63629b7e9f1940889df4b89c24382f0e
   encoding: utf-8
compression:
 blob count: 58522
  ref count: 223578
```

compression name is missing

**Comment by nikita-moor** [comment]
Hello. It's my dictionary. I think the problem is that the dictionary is stored w/o compression because it contains a lot off images in TIFF G4 format (can't access the repository right now to check it for sure):

```python
import slob
with slob.create(filename, compression="") as slb:
    slb.add(
        definition.encode("utf-8"),
        *headwords,
        content_type="text/html;charset=utf-8"
    )
```

**Comment by itkach** [comment]
> I think [slob library](https://github.com/itkach/slob) does allow it:

**Comment by itkach** [comment]
> I think [slob library](https://github.com/itkach/slob) does allow it:
 
Indeed. But Java implementation doesn't support this :) 

Using zlib should incur negligible overhead though, even if it doesn't ultimately decrease dictionary size, no reason not to use it. It seems to me that use of TIFF is way more problematic. Dictionary content is typically rendered/viewed with a web browser (desktop or embedded like WebView on Android) and no mainstream browser supports TIFF (other than perhaps Safari?).
