### ISSUE TITLE
(Android 14) App Crash after Start

### ISSUE THREAD

**Issue by RDusr05** [itkach/aard2-android#172]
The app crashes immediately after starting on Android 14. 
It is no longer possible to use it. :(

**Comment by condenseinform** [comment]
Here's a crash log from my device.
* Android 14, UQ1A.231205.015
* Google Pixel 6 Pro
* Aard 2 version 0.54 installed from F-Droid today
* crash occurs upon first launch
```
type: crash
osVersion: google/raven/raven:14/UQ1A.231205.015/2023120800:user/release-keys
package: itkach.aard2:54
process: itkach.aard2
processUptime: 108 + 199 ms
installer: com.android.packageinstaller

java.lang.RuntimeException: Unable to create application itkach.aard2.Application: java.lang.RuntimeException: Failed to start web server
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7042)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2248)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8216)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: java.lang.RuntimeException: Failed to start web server
	at itkach.aard2.Application.startWebServer(Application.java:220)
	at itkach.aard2.Application.onCreate(Application.java:112)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1321)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7037)
	... 11 more
Caused by: java.net.SocketException: Permission denied
	at sun.nio.ch.Net.socket0(Native Method)
	at sun.nio.ch.Net.serverSocket(Net.java:424)
	at sun.nio.ch.ServerSocketChannelImpl.<init>(ServerSocketChannelImpl.java:88)
	at sun.nio.ch.SelectorProviderImpl.openServerSocketChannel(SelectorProviderImpl.java:56)
	at java.nio.channels.ServerSocketChannel.open(ServerSocketChannel.java:113)
	at org.simpleframework.transport.connect.SocketAcceptor.<init>(SocketAcceptor.java:95)
	at org.simpleframework.transport.connect.SocketListener.<init>(SocketListener.java:81)
	at org.simpleframework.transport.connect.SocketListenerManager.listen(SocketListenerManager.java:98)
	at org.simpleframework.transport.connect.SocketListenerManager.listen(SocketListenerManager.java:81)
	at org.simpleframework.transport.connect.SocketConnection.connect(SocketConnection.java:106)
	at itkach.slobber.Slobber.start(Slobber.java:578)
	at itkach.aard2.Application.startWebServer(Application.java:210)
	... 14 more
```
Thank you for your work developing Aard 2!

**Comment by itkach** [comment]
Looks like this is the same as #173.
