### ISSUE TITLE
Aard crash with no network permissions

### ISSUE THREAD

**Issue by starbrights** [itkach/aard2-android#195]
Have latest version from FDroid with a big Wiki slob file. It works - until I removed permission for network.
But it is indended to use offline.
This is happen on Graphene OS (Android 15), while in LOS 21 (A 14) this is no issue ?!?

```
type: crash
osVersion: google/bluejay/bluejay:15/AP4A.241205.013/2024121200:user/release-keys
flags: dev options enabled
package: itkach.aard2:58, targetSdk 34
process: itkach.aard2
processUptime: 173 + 351 ms
installer: com.stevesoltys.seedvault

java.lang.RuntimeException: Unable to create application itkach.aard2.Application: java.lang.RuntimeException: Failed to start web server
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7631)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2458)
	at android.os.Handler.dispatchMessage(Handler.java:109)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8826)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: java.lang.RuntimeException: Failed to start web server
	at itkach.aard2.Application.startWebServer(Application.java:229)
	at itkach.aard2.Application.onCreate(Application.java:112)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1398)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7625)
	... 11 more
Caused by: java.net.SocketException: Permission denied
	at sun.nio.ch.Net.socket0(Native Method)
	at sun.nio.ch.Net.serverSocket(Net.java:424)
	at sun.nio.ch.ServerSocketChannelImpl.<init>(ServerSocketChannelImpl.java:88)
	at sun.nio.ch.SelectorProviderImpl.openServerSocketChannel(SelectorProviderImpl.java:56)
	at java.nio.channels.ServerSocketChannel.open(ServerSocketChannel.java:113)
	at org.simpleframework.transport.connect.SocketAcceptor.<init>(SocketAcceptor.java:95)
	at org.simpleframework.transport.connect.SocketListener.<init>(SocketListener.java:81)
	at org.simpleframework.transport.connect.SocketListenerManager.listen(SocketListenerManager.java:98)
	at org.simpleframework.transport.connect.SocketListenerManager.listen(SocketListenerManager.java:81)
	at org.simpleframework.transport.connect.SocketConnection.connect(SocketConnection.java:106)
	at itkach.slobber.Slobber.start(Slobber.java:578)
	at itkach.aard2.Application.startWebServer(Application.java:219)
	... 14 more
```

**Comment by itkach** [comment]
See #173

**Comment by starbrights** [comment]
Ok thanks for clarification, although I not completely understand why it has this permissions in GOS, but not other for others LOS,AOSP.
