### ISSUE TITLE
Running app

### ISSUE THREAD

**Issue by KGRYG** [itkach/aard2-android#78]
Hi I followed instructions in [readme](https://github.com/itkach/aard2-android#developing) and after I install project and try to run(I'm using Android Studio 3) on emulator I have error:

`java.lang.RuntimeException: Unable to start activity 
ComponentInfo{itkach.aard2/itkach.aard2.MainActivity}: 
java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x3
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                     at dalvik.system.NativeStart.main(Native Method)
                                                  Caused by: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x3
                                                     at android.content.res.TypedArray.getDimension(TypedArray.java:399)
                                                     at com.shamanland.fonticon.FontIconDrawable.inflate(FontIconDrawable.java:111)
                                                     at com.shamanland.fonticon.FontIconDrawable.inflate(FontIconDrawable.java:65)
                                                     at itkach.aard2.MainActivity.onCreate(MainActivity.java:71)
                                                     at android.app.Activity.performCreate(Activity.java:5231)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:136) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5017) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:515) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                     at dalvik.system.NativeStart.main(Native Method)`

**Comment by KGRYG** [comment]
I found issue:
it's Android Studio 3 there is some bug which causing this error, if you run app on Android Studio 2.3.3 it works just fine.

**Comment by itkach** [comment]
@KGRYG thank you for investigating

**Comment by itkach** [comment]
Fixed in 6a5f96341e32f43ea15d8b9ed774900ab15ab3e0
