### ISSUE TITLE
App crashes after loading a dictionary

### ISSUE THREAD

**Issue by wocard2** [itkach/aard2-android#99]
Immediately after loading a dictionary (either selected manually or found by scanning), the app (version 2.0.43) crashes. All further invocations will crash immediately, without any interaction. Here's the exception stack:

    E/AndroidRuntime: FATAL EXCEPTION: main
        Process: itkach.aard2, PID: 4965
        java.lang.ArithmeticException: divide by zero
            at java.util.Formatter$FormatSpecifier.localizedMagnitude(Formatter.java:4210)
            at java.util.Formatter$FormatSpecifier.print(Formatter.java:3140)
            at java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:2828)
            at java.util.Formatter$FormatSpecifier.print(Formatter.java:2786)
            at java.util.Formatter.format(Formatter.java:2491)
            at java.util.Formatter.format(Formatter.java:2426)
            at java.lang.String.format(String.java:2670)
            at itkach.aard2.DictionaryListAdapter.setupBlobCountView(DictionaryListAdapter.java:232)

This looks like https://bugs.openjdk.java.net/browse/JDK-8196399. (I don't know which locale my device is using.)

**Comment by itkach** [comment]
Do you know what language your device's user interface is using? Also which
version of Android? Does the crash go away if you change device's UI
language?

**Comment by wocard2** [comment]
The interface language is "English (United States, Computer)" (that's probably en_US_POSIX), the Android version is 7.1.1. Changing the device's UI language to "English (United States)" makes the crash go away. Thainks for pushing me in that direction.
